[project]
name = "my-packages"
version = "0.1.0"
authors = [
  { name="cocobongo" }
]
description = "Shared tools for different projects"
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
